load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronous priority.
# After projects get larger, it's better to disable to save some time.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Fix for Google Maps or other plugins that might need specific ARC or deployment targets
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
